### ISSUE TITLE
Racing

### ISSUE THREAD

**Issue by Kristoffermyr** [InZidiuZ/op-framework-bug-tracker#102]
Adding the command /race (amount/cash)for more races happening.

**Comment by Kristoffermyr** [comment]
Then we dont have to wait for staff to do an organized race with a pot

**Comment by InZidiuZ** [comment]
Hey,

I've made a script which allows for this. To use it, do /race [amount], it'll then automatically remove cash from you & let nearby drivers join in on the race. For every person that joins, the prize becomes bigger, winner takes it all. You can test this out for yourself after next patch, though.

[Here's](https://gyazo.com/79c263809cf40ea3f8978602a43b6f4b) how to start a race.

**InZidiuZ**
*OP-FW Developer*
