### ISSUE TITLE
garbage job

### ISSUE THREAD

**Issue by tankfurious** [InZidiuZ/op-framework-bug-tracker#103]
run garbage for 3 hours and the only minor issues i could find was

1/ spawning trucks on each other.

could you add the clear area thing before another is aloud to spawn.

2/not always getting a notification when you find an item.

like i said minor issues, everything else works perfect.

**Comment by InZidiuZ** [comment]
Hey,

1. This should rarely be an issue as there's a check for it, but if the check bugs out frequently, make sure you take a look at the spawn point before starting the job.
2. This shouldn't be an issue as both of those actions happens at the same time. I've made it a more distinct green though, so hopefully you won't miss it again, if that's what happened. ;)

**InZidiuZ**
*OP-FW Developer*
