### ISSUE TITLE
Admin Teleport Issues

### ISSUE THREAD

**Issue by N8teZero** [InZidiuZ/op-framework-bug-tracker#104]
Reporter: Nate

Summary: The teleport commands in the admin menu are buggy. I don't think Teleport to Me works at all, and Teleport to Player doesn't work while spectating them. 

Steps to Reproduce: Open admin menu, select a player, click Teleport to Me, nothing happens. Spectate them and click Teleport to Player, nothing happens. Exit spectate and click Teleport to Player and it sometimes works.

**Comment by InZidiuZ** [comment]
Hey,

> I don't think Teleport to Me works at all

Yes, yes it does...

I've made some changes to make the menu a little better though. If you teleport (to) someone while spectating, it'll automatically cancel the spectate making sure the teleport goes through. I also found a way for staff to go invisible for all clients when spectating, and also reduced the distance between the target & spectator so whispers can be heard as well.

**InZidiuZ**
*OP-FW Developer*
