### ISSUE TITLE
Add Grocery store at Harmony/Route 68

### ISSUE THREAD

**Issue by essjaybee** [InZidiuZ/op-framework-bug-tracker#105]
Name: OMGPointless#1823

Summary: Don't know if this is the right forum, maybe you know already and it's WIP. Came across this store while I was trucking, and was hungry. Seems like it should have a blip and a friendly NPC guy?

Reason: Just makes sense for Harmony to have one, considering the assets etc are already there.

![20190628023659_1](https://user-images.githubusercontent.com/2750716/60309467-378d0b80-994e-11e9-8855-bad26691701f.jpg)
![20190628023709_1](https://user-images.githubusercontent.com/2750716/60309470-3a87fc00-994e-11e9-93fd-2d8f6cffd7c1.jpg)
![20190628023721_1](https://user-images.githubusercontent.com/2750716/60309474-3c51bf80-994e-11e9-881e-738f2b665f22.jpg)

**Comment by InZidiuZ** [comment]
Hey,

I must've missed it when adding the locations! Thanks for letting me know though, and yep, this is definitely the right place to post this. This location will be added after the next patch, so will close this.

**InZidiuZ**
*OP-FW Developer*
