### ISSUE TITLE
Weed grow

### ISSUE THREAD

**Issue by thefinalgamer** [InZidiuZ/op-framework-bug-tracker#106]
Feel like people are just grindin picking the weed, so maybe like a nopixel style where you need to buy plant pots or use plastic to make it / get weed seeds female /male and you have to look after them in your crib ? Maybe you can buy a warehouse and you can share the keys with friends and pay rent on it and stuff ?

**Comment by essjaybee** [comment]
Just want to chime in. Obviously this needs to well implemented etc, but if it's possible, I would absolutely love it. And the people in my group agrees. For me it's the extra touches that adds to the character, and even if it only 1oz yields it would add alot to city life.

Don't know what the planes are in the future. But personally I'm crossing my fingers for a little tiny shack or warehouse up at Sandy where I can grow plants. Keep the dream alive!

**Comment by InZidiuZ** [comment]
Hey,

This is definitely something that is being discussed & planned, and with no doubt, it'll be a thing at some point.

But, we're still a week into this new framework, and we still lack a lot of vital features that would be required for this, such as a proper housing system w/custom interiors, raids, etc. Therefor, I will close this, as this is still months away, but I can guarantee this will be a thing, eventually.

**InZidiuZ**
*OP-FW Developer*
