### ISSUE TITLE
In game time on phone

### ISSUE THREAD

**Issue by thinkclint** [InZidiuZ/op-framework-bug-tracker#109]
**Name:**
Think Clint

**Summary:**
I believe the in-game phone has real-world time on it. Right now (I believe) I only see in-game time when I'm in a vehicle, and not when I'm just walking around. It'd be nice for the phone to have in-game time so you can check it when there isn't a vehicle around.

**Reason:**
Reasons.

**Comment by InZidiuZ** [comment]
Hey,

I agree. This has now been changed, and will go live with the next patch.

**InZidiuZ**
*OP-FW Developer*

**Comment by thinkclint** [comment]
Cool! I'm a UI/UX designer, so I may pass along some suggestions every once in a while. I don't always know feasibility, so please feel free to let me know if anything I suggest is absurd, or I'm being an ass.
