### ISSUE TITLE
Phone's bank app displaying Maze bank balance

### ISSUE THREAD

**Issue by 94cents** [InZidiuZ/op-framework-bug-tracker#11]
**Reporter:**
foo#5910

**Summary:**
Using Bank app on phone displays incorrect bank balance as Maze bank.
 
**Steps to Reproduce:**
Go to Bank app in phone.

**Expected Results:**
Display bank balance from new banking. 
 
**Actual Results:**
Display Maze Bank and balance of $0.

**Comment by InZidiuZ** [comment]
This issue has been resolved. The app will now display your actual bank balance.
