### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by XeineZ** [InZidiuZ/op-framework-bug-tracker#111]
**Reporter:**
Xz#5620

**Summary:**
Change the script for certain vehicles or find a fix for them

**Steps to Reproduce:**
Try to repair rear tires of phantom
**Expected Results:**
Be able to fully repair the truck

**Actual Results:**
Rear tires stay popped

## Additional Information

**Notes:**

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved. The fix for it will go live after next patch.

**InZidiuZ**
*OP-FW Developer*
