### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-bug-tracker#112]
**Reporter:**
SteezyRen#2828

**Summary:**
Fueling cars seem to get glitched whenever you start fueling with someone in the vehicle

**Steps to Reproduce:**
- Go to gas station
- Have friend in passenger seat
- start pumping gas

**Expected Results:**
Gas goes up while taking your money. Also not entirely sure on how to fix the vehicle as when they step out the gas seems to be bugged in the same spot. 

**Actual Results:**
Gas does not go up. 

## Additional Information

**Screenshots:**
Shit.. don’t have screenshots of F8 console as I’m typing this up on my phone. I will recreate this bug report in the event that it becomes necessary to fix this issue.

**Comment by essjaybee** [comment]
this also seems to depend on where your passenger is in relation to the gas pump. for example, I've had fuels where my idiot friend Emilio won't get out of the car, and he's right next to the pump as passenger, and the meter would bug out, until he got out. I've had other moments where he's been in the car but I've taken the fuel pump on the vehicle's left side, and it let me pump normally.

Additionally, the same issue can happen even with nobody in your vehicle. Sometimes you have to get in and out and drive a little bit. I had one that just went bonkers and I left the block and came back and it worked.

Alot of this is empirical like you can tell, but there are some details to figure out.

**Comment by InZidiuZ** [comment]
Hey,

I wasn't able to reproduce this in the exact same way as you. But after some testing, I did find some flaws with the sync surrounding the fueling part, and have created a workaround for it. The workaround should make the fuel sync in live time for any potential passengers. I've done minimum testing with this though, so if it doesn't resolve the issue, please comment here again so I can reopen this.

**InZidiuZ**
*OP-FW Developer*
