### ISSUE TITLE
No Return When Doing /checkplate

### ISSUE THREAD

**Issue by ShelbsShelbs** [InZidiuZ/op-framework-bug-tracker#117]
**Reporter:**
Who is reporting this? Please include discord name.
Shelbs#9300

**Summary:**
Write a short summary of what you're experiencing.
Unable to /checkplate specific license plate: 66HNG951 but nothing happens when you do so. We also tried on our police cars in the area and the /checkplate worked fine on them. I believe the vehicle is a Fusilade or a Feltzer.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Try to /checkplate specific license plate: 66HNG951

**Expected Results:**
What are the expected results?
Have the plate return to a name when performing a /checkplate

**Actual Results:**
What are the actual results?
Nothing returned on specific car (Fusilade or a Feltzer)  but did when tested on the officer's cars in the same area.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
Video of it... no F8 console for it though... https://plays.tv/video/5d16f04961ebd5ac91/cant-run-plate-

**Game Resolution:**
What is your game's resolution?
Irrelevant

**Player Data:**
Write /info whilst ingame and provide the information you're given.
Irrelevant? Character ID 3 though. happened to all cops that were on duty at the stop.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

Reason behind this is that the car with "66HNG951" belonged to a character which had recently been deleted, which caused the system to bug out & not give any response. This was fixed yesterday though, and will be live after next patch.

**InZidiuZ**
*OP-FW Developer*
