### ISSUE TITLE
characters reset when relog

### ISSUE THREAD

**Issue by tankfurious** [InZidiuZ/op-framework-bug-tracker#12]
if you change/add any accessories from cloths store to you charactor when you next relog the charators skin/ gender/ face changes each time. i have managed to recreate this bug just by getting a hair cut or adding earings completely changes your charactor (not cloths)

also whe you change texture of shirt a bag is added to your costume
other texture changes also add random clothing items

**Comment by InZidiuZ** [comment]
What model were you using? The GTA online one, or an NPC?

**Comment by InZidiuZ** [comment]
This issue _should_ be fixed, I'm unable to replicate it, anyways. If the issue persists, please DM me on discord.
