### ISSUE TITLE
Garbage Truck Keys

### ISSUE THREAD

**Issue by Valkrium** [InZidiuZ/op-framework-bug-tracker#121]
**Name:**
Roastedddd#2903

**Summary:**
When you get the garbage truck it gives you the key to that specific work truck. But when you go to turn in your truck for a payment the truck disappears with the keys to that truck don't. So they just add up each time you do a job.

**Comment by InZidiuZ** [comment]
Hey,

This issue will be resolved after next patch.

**InZidiuZ**
*OP-FW Developer*
