### ISSUE TITLE
/me with capital letters

### ISSUE THREAD

**Issue by N8teZero** [InZidiuZ/op-framework-bug-tracker#122]
**Reporter:**
capsure#0737 & Nate

**Summary:**
When using /me, some capital letters do not show up in the message. I have not personally tried/tested this, but have had a few people report it to me. Will include screenshots when I am able to get online and test.

**Comment by InZidiuZ** [comment]
Do they become lower case letters, or do they actually disappear? Making them go lower case was intentional, but not removing them from the message entirely.

**Comment by N8teZero** [comment]
From my understanding, either the whole message shows as empty, or the capital letters don't show at all.

**Comment by iMStokes** [comment]
The letter that is Capitalized is missing. The rest of the message shows. I can confirm this from EMS experience. "D" never shows. So "DOA" becomes "OA". However lower case d's will show. This happens with another certain letter, but cannot recall it atm.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved, you should be able to type with uppercase letters without issue after next patch.

**InZidiuZ**
*OP-FW Developer*
