### ISSUE TITLE
Garbage Job GPS

### ISSUE THREAD

**Issue by iMStokes** [InZidiuZ/op-framework-bug-tracker#124]
**Reporter:**
@Stokes#8745

**Summary:**
After finishing some Garbage runs - whenever you turn in your truck the green GPS that leads to the door to get a new job never disappears. So once you're done with your Garbage job the GPS forever leads back to the HQ. The only way it seems to get rid of it is to log or "catch a train" out of the city and back. 

**Steps to Reproduce:**
Do a Garbage job. Turn in your truck. Leave. 

Unsure if I'm simply missing a step to end this GPS issue - as a lot of people have said the same thing. Just gets in the way unless you're ending your RP experience and run with the job rather than doing it at the beginning or in the middle. If you need Screenshots of anything, just let me know - and I can grab them next time im on!

**Comment by InZidiuZ** [comment]
Hey,

This issue should be resolved after next patch.

**InZidiuZ**
*OP-FW Developer*
