### ISSUE TITLE
Add a /patdown

### ISSUE THREAD

**Issue by FossiiLs** [InZidiuZ/op-framework-bug-tracker#125]
**Name:**
Who is suggesting this? Please include discord name.
FossiiLs_#4043 | Senior Trooper Alex Stone
**Summary:**
Write a short summary of what your suggestion is about.
I believe the SASP should have a /pat down command so if a Trooper arrives on scene of lets say a shooting, we can detain the people who are on scene and instead of doing a complete search of someone we can pat them down. Let's say I do the /pat down and if someone has a gun on them it'll state at the top right with Gun Found or something along the lines of that. 
**Reason:**
Why would your suggestion be a good addition to Legacy?
This option can add more roleplay to the server in which people wont be so scared to be patted down just in case they have marijuana or cocaine on them which usually involves them just running away. It would also help to make sure that no illegal searches are completed. Let's say I find a gun, I can then question them about the situation and once the GSR test are implemented then it will help gather all the evidence needed for either an arrest or a release of the potential suspect.

**Comment by InZidiuZ** [comment]
Can't you just say you're patting them down, /search them and then ignore any other illegal items but guns? 🤔

**Comment by FossiiLs** [comment]
Yes but I believe it would remove temptation. I mean your the boss man. Just a suggestion. Thanks for reading it though!

**Comment by InZidiuZ** [comment]
Closing as I don't think this will be added, I'd rather spend time on things we can't already do. ;)
