### ISSUE TITLE
Police Officer, /Escort Bug - Video

### ISSUE THREAD

**Issue by RGDaviid** [InZidiuZ/op-framework-bug-tracker#13]
**To make this more clear i have Included a YouTube Video showcasing the issue with the F8 Console too.**

- In the Police commands, /Escort seems to bug a lot. It sometimes escorts the person and other times it doesn't. 

- When it fails to Escort but the police officer is close to the player. The script does "Escort = True". This means that the Officer cannot run as shown in the video. The officer cannot run even if he doesn't have a suspect in hand.

- If "Escort = False" Then the officer can run as usual.

This short video hopefully explains this in better Detail.

https://youtu.be/srkFrcsl1gs

**Comment by InZidiuZ** [comment]
Appreciate the report. The issue has been resolved.
