### ISSUE TITLE
Discord invite link displayed in game

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-bug-tracker#130]
**Name:**
SteezyRen#2828

**Summary:**
Having the discord invite link displayed in game on the top left. 

**Reason:**
It's almost completely necessary for anyone who plays in a RP server to have access to the discord.
- Contact staff or voice chat with them
- Applications
- Link to github
- etc.

**Comment by InZidiuZ** [comment]
Hey,

I've added a "trademark" with the discord link in the upper-left corner. This is by default shown, but can be toggled using /discord. This action will save after disconnecting too.

**InZidiuZ**
*OP-FW Developer*
