### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by RemedyUK** [InZidiuZ/op-framework-bug-tracker#131]
**Name:**
Remedy#2078

**Summary:**
Enhanced Turbo waste gate (dump valve) noises need to be added

**Reason:**
Because turbo woooooooooooo-tsss

**Comment by InZidiuZ** [comment]
Hey,

Didn't find any good way to do this, so probably not. If you do find one though, feel free to comment here. I bet it's possible client-side, but not sure how doable it's server-side. Closing this, though.

**InZidiuZ**
*OP-FW Developer*
