### ISSUE TITLE
Custom motorcycles 

### ISSUE THREAD

**Issue by SATIN187** [InZidiuZ/op-framework-bug-tracker#132]
**Name:**
Who is suggesting this? Please include discord name.
SATIN187(Jimmy McGuinness)

**Summary:**
Write a short summary of what your suggestion is about.
Woul dit be possible to get some custom motorcycles? i would love to see like a Harley street glide to buy

**Reason:**
Why would your suggestion be a good addition to Legacy?
Adding custom bikes like Harleys would be nice for a motorcycle gang

**Comment by InZidiuZ** [comment]
Hey,

Currently not doing vehicle suggestions. But, I know Karpenko will be working on imports soon, and believe he said he's open to suggestions, so feel free to DM him any suggestions you may have.

**InZidiuZ**
*OP-FW Developer*
