### ISSUE TITLE
Phone Texting Glitch - Video

### ISSUE THREAD

**Issue by RGDaviid** [InZidiuZ/op-framework-bug-tracker#14]
**I have included a YouTube Video which showcses the bug i'm speaking about here**

- When you're writing a message in your phone, It still allows your Keybinds to do they're assigned function. Such as change camera angles(V), Voice distance (G) and taking the phone in and out(P). 

- The video does quite a good job of Showcasing this Bug.

- Another Minor bug is the "Dark Chat". Once you click the  app it's title is spelt incorrectly. It's something like "Dark Tchat". <--- Very Minor Spelling Error. 

https://youtu.be/CoOp08TtQ34

**Comment by InZidiuZ** [comment]
Appreciate the report. The issues noted have now been resolved.
