### ISSUE TITLE
EMS bug

### ISSUE THREAD

**Issue by Cironite** [InZidiuZ/op-framework-bug-tracker#15]
When you Escort someone and they are down on the ground, to the Check In and Check them In
you will be put in the bed with them

**Comment by InZidiuZ** [comment]
Could you be a bit more descriptive?

**Comment by Cironite** [comment]
I knocked my friend down on the ground to test some EMS Features such as
escort, and i escorted them to the hospital, note that she is still down on
the ground and i am still escorting, when i try to check her in, it checks
us both me and her, we both get teleported to the same bed and we both get
out of the bed at full hp, as you can see the issue here is that it is
supposed to Put her alone on the bed and not both of us.

**Comment by InZidiuZ** [comment]
That is not how you check  someone in. As an EMS, you must do /cpr to revive them. If you bring them to the hospital, you must let them check in themselves.
