### ISSUE TITLE
Create a character bugs

### ISSUE THREAD

**Issue by PanchoGarcia** [InZidiuZ/op-framework-bug-tracker#16]
Reporter: Pancho#0001

Summary: You can put way too many numbers in the age field for creating a character
Steps to Reproduce: Type numbers in the D.O.B. and it won't limit you appropriately for the (yyyy) field 
Expected Results: too many numbers will fit

Actual Results: Too many numbers

------------------------------------------------------------------------------------------------------

Reporter: Who is reporting this? Pancho
Summary: No glasses option in creating a character

Steps to Reproduce: Make a character.

Not sure if its intended or not

**Comment by InZidiuZ** [comment]
Noted. For future reports, though, please create one report per issue. The "no glasses option" will be looked into, but won't guarantee anything as the current clothing menu is a little messy.

**Comment by InZidiuZ** [comment]
This has now been resolved. You now also _have_ to put something into all the fields, otherwise it won't let you create a character.
