### ISSUE TITLE
Cocaine bug?

### ISSUE THREAD

**Issue by VTechas** [InZidiuZ/op-framework-bug-tracker#17]
When i took the plane out, my friend got in the drivers seat and left, and when i got in there i didnt see the airdrop on my map and neither did he so it just disappeared. I don't know if its intended just throwing it out there

**Comment by InZidiuZ** [comment]
Don't believe this should happen, are you able to replicate it?

**Comment by Ronilf** [comment]
I tried to do a run last night 06-7-2019 paid for plane it spawned. By the Time i got into the plane it stated i had already failed the mission. I didnt even get to run to drop area or anything just failed mission right as i started it

**Comment by Ronilf** [comment]
So just failed a mission again after just picking it up. It seems that if you fail once and try to go back it auto fails your next attempt. This is the same way it failed for me the first time. 06-09-2019

**Comment by InZidiuZ** [comment]
Pushing a possible fix for this in the next version, so see if it continues to happen then. Also, make sure to always screenshot your F8 console for any debug info.

**Comment by Ronilf** [comment]
I will try and replicate this some time this week/weekend but need to get the funds to do so

**Comment by InZidiuZ** [comment]
This might, hopefully, be solved in 1.8. Got some good debug data from a guy, so I _believe_ I've got it fixed, but I'll leave this issue open for a couple more days to see if anyone reports anything.

**Comment by InZidiuZ** [comment]
This shit has finally been fixed. Closing.
