### ISSUE TITLE
semi trucks 

### ISSUE THREAD

**Issue by codles1829** [InZidiuZ/op-framework-bug-tracker#18]
semi trucks fall from the sky sometimes when you take them out of your garage

**Comment by InZidiuZ** [comment]
At which garages? Need some more information to solve that...

**Comment by codles1829** [comment]
i noticed it happens at all of them if you retrieve the vehicle and it seemed to be any vehicle now that i've retrieved other vehicles

**Comment by InZidiuZ** [comment]
This issue should be resolved with the next version.
