### ISSUE TITLE
Template (Must Use!)

### ISSUE THREAD

**Issue by InZidiuZ** [InZidiuZ/op-framework-bug-tracker#2]
[Here's](https://pastebin.com/6H2RD7y9) a link to this on a pastebin.

**Reporter:**
Who is reporting this? Please include discord name.

**Summary:**
Write a short summary of what you're experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## More Info

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by RGDaviid** [comment]
**Reporter:**
Davidk#2271

**Summary:**
When taking a weapon (a knife in my example) it stays in your back but also spawns another one in your hand.

**Steps to Reproduce:**
Just take it out of my Inv

**Expected Results:**
i expected for it to be removed from my back as i took it out. 

**Actual Results:**
Spawned another one in my hand. and kept the other one on my back.

## More Info

**Screenshots:**

**Game Resolution:**
1920x1080

**Player Data:**
doing /info i got 
Error running system event handaling function for resource op-base: citizen:/scripting/lua/scheduler.lua:41: Failed to ewxect
	stack traceback:
		commands/commands_server.lua:73: in upvalue "handler"
		citizen:/scripting/lua/scheduler/lua:219: In function <citizen:scritping:/scripting/lua/scheduler.lua:218>
	stack traceback:
		[C]: in funcction "error"
		citizen:/scipting/lua/scheduler.lua:41: in field  "CreateThreadNow"
		citizen:/scripting/lua/scheduler.lua:218: in function <citizen:scritping/lua/scheduler.lua:182>
**Notes:**
Can't paste the photo in :(
![image](https://user-images.githubusercontent.com/40771170/52525789-b686ed80-2ca6-11e9-91b2-7925876f630f.png)
