### ISSUE TITLE
Vehicle repairs use all materials

### ISSUE THREAD

**Issue by sammikins** [InZidiuZ/op-framework-bug-tracker#20]
Scenario: Your repair requires one material for a repair (One Scrap for instance) and you have more than needed material for that repair (Ten scrap) on your person while you make the repair, all of the extra materials will be consumed on the repair. So far, it has done this for all of the materials I've required. (Scrap and Steel)

This seems to only be a problem with repairing the car directly and not with the workbench. Item construction, such as windows, doors, and and wheels seem to be working as intended and do not consume additional materials.

**Comment by InZidiuZ** [comment]
This issue has been resolved.
