### ISSUE TITLE
No way to efficiently repair semi trucks

### ISSUE THREAD

**Issue by sammikins** [InZidiuZ/op-framework-bug-tracker#22]
There is currently no efficient way to repair a semi truck. It doesn't fit into the garage for repairs and the only way to repair it is with repair kits which is very inefficient and expensive. This makes the transporter job a little bit difficult to upkeep.

**Comment by Ronilf** [comment]
Go To Benny's by PDM or Mechanic shop Semis fit into those locations

**Comment by InZidiuZ** [comment]
A secondary repair shop, one less accessible and bigger, could be possible for larger vehicles. Possibly down at the trucker terminal.

**Comment by Ronilf** [comment]
That would be nice went into Mechanic last night and was scrapping the ceiling with my truck. It was so damaged that in the process of pulling in it disabled my truck, had to blow it up and get it back via recovery

**Comment by InZidiuZ** [comment]
A secondary repair shop will be added with the next version, located at the trucking terminal, as I still want to encourage use of the one near grove street.
