### ISSUE TITLE
Backpacks don't timeout

### ISSUE THREAD

**Issue by sammikins** [InZidiuZ/op-framework-bug-tracker#23]
I'm pretty sure this is known, but it's not submitted. Submitting just in case. When dropping items on the ground a backpack is placed, after picking up the item the empty backpack is left behind. Empty backpacks don't seem to timeout and stay visible around the world seemingly forever.

**Comment by InZidiuZ** [comment]
Empty backpacks now time out after 60-120s of being empty.
