### ISSUE TITLE
Bad Trailer Spawn at Paleto Transporter pick up

### ISSUE THREAD

**Issue by Ronilf** [InZidiuZ/op-framework-bug-tracker#24]
The Trailer Spawns in on top of the awning and you have to move it around with the Semi truck. i Have broken my truck several times moving trailer to where i can get hooked onto it.
![Bug 1](https://user-images.githubusercontent.com/51394914/58931437-4b659900-8725-11e9-88b9-79c55f16b1c7.JPG)

**Comment by InZidiuZ** [comment]
This issue has been resolved.
