### ISSUE TITLE
Chop Shop Vehicle Bug

### ISSUE THREAD

**Issue by RGDaviid** [InZidiuZ/op-framework-bug-tracker#25]
Reporter: Who is reporting this? Karpenko

Summary: Write a short summary of what you're experiencing. If the Chop Shop vehicle has Blown up or get's impounded we cannon get a new vehicle to look for. Instead it asks for the same vehicle that's now blown up. 

Steps to Reproduce: Include what steps that are needed in order to reproduce the issue. 1. Find the vehicle... 2. Crash really badly (Blow it up)... 3. Use the radio to get a new car but instead you get the same one. 

Expected Results: What are the expected results? Expected a new vehicle to be listed. 

Actual Results: What are the actual results? The same vehicle that's Exploded is shown.

**Comment by InZidiuZ** [comment]
The hot vehicle is only hot for 30 minutes, so if it blows up (or anything else happens to it), the chopshop will choose a new vehicle after the timer has gone by, so it shouldn't _really_ be an issue.
