### ISSUE TITLE
SMG turning into Knuckledusters

### ISSUE THREAD

**Issue by ShelbsShelbs** [InZidiuZ/op-framework-bug-tracker#26]
SMG turned into 2 sets of knuckledusters after using K to pick up items from a backpack, then eating without bringing over to inventory. I've included a clip of this happening with f8 console in case needed. 

https://plays.tv/video/5cf71fa78e367ad958/smg-to-knuckledusters-

**Comment by InZidiuZ** [comment]
Try splitting the knuckledusters, not exactly sure what causes this, but no items should get lost. Should be solvable, just gotta find out exactly where the issue is.

Splitting the two knuckledusters, then reopening your inventory or relogging should solve it.
