### ISSUE TITLE
Character Skinning: "Head" and "Hair" in wrong section

### ISSUE THREAD

**Issue by sammikins** [InZidiuZ/op-framework-bug-tracker#27]
While skinning a character, the "Head" and "Hair" slots are confusingly in the "Clothing" section. It would make more sense to put these in the "Face" section, if possible.

**Comment by sammikins** [comment]
Maybe rename "Face" to "Head"?

**Comment by InZidiuZ** [comment]
Plan is to rewrite the clothing system in a few days, so that should get this resolved.

**Comment by InZidiuZ** [comment]
Didn't end up rewriting it, but fixed a bunch of issues with it & added /mask and /glasses.
