### ISSUE TITLE
Chop shop delivery bug

### ISSUE THREAD

**Issue by sammikins** [InZidiuZ/op-framework-bug-tracker#29]
When you deliver a car to the chop shop, it seems you need to use the radio to confirm that the car is hot before the delivery will be accepted. It will not accept the car delivery unless I use the radio immediately before dropping the car off at the chop shop. I don't know if this is intentional.

**Comment by InZidiuZ** [comment]
You don't need to use the radio to confirm that the car is hot.

**Comment by sammikins** [comment]
For some reason it would not accept the car until we radio'd. I'm unsure why this is happening.

**Comment by InZidiuZ** [comment]
Going to close this as I've made a bunch of changes to the chop shop in 1.8.
