### ISSUE TITLE
Stuck in car

### ISSUE THREAD

**Issue by liner601** [InZidiuZ/op-framework-bug-tracker#3]
**Reporter:**
Liner60#6841

**Summary:**
Tried hotwiring a car, clicked it around 7-8 times, tried to get out, took off belt didn't work.

**Steps to Reproduce:**
1. get in random car.
2. Have it say you can't figure it out
3. attempt to hotwire it 7-8 times
4. take off the seatbelt
5. Can't get out

**Expected Results:**
Being able to get out of the car

**Actual Results:**
Stuck in car

**Comment by liner601** [comment]
I realized the issue was because I locked the car using l, dismiss this.

**Comment by InZidiuZ** [comment]
Problem was solved by the reporter, closing the issue.

**Comment by InZidiuZ** [comment]
Problem was solved by the reporter, closing the issue.
