### ISSUE TITLE
Issues with Phone (They just don't work) (Video)

### ISSUE THREAD

**Issue by sammikins** [InZidiuZ/op-framework-bug-tracker#31]
* When you try to input a contact and press "Backspace" to clear the field. Backspace will end up closing the phone
* If you go to the start of the text and try to "Delete" key the field away and type in a contact name, it does not accept the field
* If you try to manually enter a phone number to connect a phone call, the person who is supposed to receive the call does not get a response on their phone.

https://streamable.com/8cslf

**Comment by InZidiuZ** [comment]
Reinstalled the phone now, and noted issues *should* have been fixed.

* Backspace doesn't close the phone while the input field is active.
* Unable to replicate this now.
* Messages should now work between clients.

There's almost definitely going to be more issues though, so if you find any, either DM me them or create another issue.
