### ISSUE TITLE
Mechanic Shop 

### ISSUE THREAD

**Issue by Ronilf** [InZidiuZ/op-framework-bug-tracker#32]
Had an additional car spawn while getting my car fixed. Then upon exiting repaired car it was in the are and fell once i went to drive off breaking all windows.
![Bug 2](https://user-images.githubusercontent.com/51394914/59142208-12753080-8980-11e9-9153-0ee1d9f34b65.JPG)

**Comment by Ronilf** [comment]
Here is a photo of what happens when i exit the mechanic shop
![Bug 3](https://user-images.githubusercontent.com/51394914/59164657-95f46600-8ad5-11e9-8c77-aee5883669ce.JPG)

**Comment by InZidiuZ** [comment]
The duping has been resolved with the next version.
