### ISSUE TITLE
Trucking Locations for Sale

### ISSUE THREAD

**Issue by OfficerKiloTV** [InZidiuZ/op-framework-bug-tracker#34]
Suggester: @OfficerKilo#3243

Summary: In the OPFW there are a whole bunch of trucking locations for pickup / drop off. If possible, make it so players can buy / own / potentially rename these locations for RP purposes.

Reason: The trucking companies are a great way to get player owned businesses involved. Making them cost 30-100k for example means players need to have a decent foothold in game. My character Jacob O'Rourke for example took the trucker job immediately and wants to own a trucking company and start his own business. If you own the business you can withdraw profits like a bank maybe? or collect the profits whenever. Only a small portion of the profits can be paid to the business, like even 10% of an $800 cargo trip is only 80 bucks but the business gets paid if the cargo is dropped or pick up (and successfully dropped off) at the destination.

Economy: I think this will be a minimal effect on the economy. Making the businesses expensive enough will balance the return so players need to spend $30k+ to earn maybe 2-3k a day so eventually players can make good money. Another thought to prevent players from making too much is when they Buy a transport business, they can't change jobs to do anything else,

**Comment by InZidiuZ** [comment]
Hey,

An extremely in-depth & realistic system for companies is being planned, introducing a government, state, stocks, company registration & multiple *legitimate* ways to run your company. This is still far from becoming something, and this entire system would be rolled out slowly, introducing feature by feature. One of the ways you could run your company, would be buy purchasing/renting different locations such as stores, gas stations, motels, apartment complexes, trucking stations (as you said) and more.

I will close this, but I'll keep it saved. :)

**InZidiuZ**
*OP-FW Developer*
