### ISSUE TITLE
Gambling among players (OPFW)

### ISSUE THREAD

**Issue by OfficerKiloTV** [InZidiuZ/op-framework-bug-tracker#35]
Suggester: @OfficerKilo#3243

Summary: I have seen a few other servers have player run gambling like black jack and poker, and I would like to suggest this addition in the future for OPFW

Reason: This would create yet another RP thing for players to do besides hang out at legion, secret meetings, tournaments, events etc could be held on a secret or open basis. Potentially even events at the casino.

Economy: There would be no effect on the economy as it would be all risk / reward for the players involved, so no extra money is created, just transferred player to player. Alternatively, if a tournament was held, there could be a prize pool at staff discretion.

**Comment by InZidiuZ** [comment]
Hey,

Definitely something that would be great to see eventually, but as we have no interiors for this currently, it's a bit difficult to create something

As there's a GTA Online "gambling" update coming, it hopefully hits FiveM too at some point, so we'll see if we can get something done then.

Until that time though, this will be closed.

**InZidiuZ**
*OP-FW Developer*
