### ISSUE TITLE
Fallinf through Street

### ISSUE THREAD

**Issue by Ronilf** [InZidiuZ/op-framework-bug-tracker#36]
I Fell through the street and ended up in a random garage. i was coming off senora hwy and just fell. This happened when going towards grove street earlier as well. the Changelog is from senora incident didnt get one from grove street one.
![Falling 1](https://user-images.githubusercontent.com/51394914/59558634-26421780-8fbc-11e9-9e38-7ae0d7b40f7a.JPG)
![Falling 2](https://user-images.githubusercontent.com/51394914/59558635-26daae00-8fbc-11e9-8bbf-6f49ffdb8db3.JPG)
![Falling End 2](https://user-images.githubusercontent.com/51394914/59558636-26daae00-8fbc-11e9-86ff-45c2596bb395.JPG)
![fALLING END](https://user-images.githubusercontent.com/51394914/59558637-26daae00-8fbc-11e9-9548-435d3d8ebf65.JPG)

**Comment by InZidiuZ** [comment]
This is caused by GTA issues. Whenever you run out of RAM (?) some textures may not load quickly enough & same with collisions, which will cause this. A PC upgrade should fix it. ;)
