### ISSUE TITLE
Transporters not getting paid

### ISSUE THREAD

**Issue by Ronilf** [InZidiuZ/op-framework-bug-tracker#37]
Since the recent Wipe of the server, the last two days, i have not been getting paid for the jobs that i have done. I tried disconnecting and reconnect but that didn't seem to help. I currently am missing $3,400 from the jobs that i have done, i like long hauls. Attached are picture from the most recent job i took. I circled the job that i did and included my cash when picking it up. The second photo is from the turn in and the missing payment. I don't know if there is a Paycheck place i need to go to that i haven't found yet i will be looking for that as well in case i just missed it.

![No Payment 1](https://user-images.githubusercontent.com/51394914/59576179-610f8280-9084-11e9-8bd2-ea84d47aeb15.JPG)
![no payment 2](https://user-images.githubusercontent.com/51394914/59576180-610f8280-9084-11e9-9367-e260d9ea4fb6.JPG)

**Comment by InZidiuZ** [comment]
This issue has been resolved.
