### ISSUE TITLE
Having access to the Old hospital (south of legion)

### ISSUE THREAD

**Issue by Yunakochan** [InZidiuZ/op-framework-bug-tracker#38]
**Suggester:**
I am Kait Anzu, Chief of Medicine of EMS. @Yunakochan#7179

**Summary:**
I suggested to give us access to enter the Old Hospital(south of legion) so we can use it as a morgue.

**Reason:**
As EMS, we have the power to pronounce someone DOA after giving them a diagnosis. We also think that leaving the body/person in the middle of nowhere is not really Realistic, and we thought that we could bring their body to the morgue as they are dead. In murder scene, we could also RP out to try finding evidence about the person who murdered him etc.. 

**Economy:**
I don't think it will have an Economy impact, just a big RP impact for EMS.

**Comment by InZidiuZ** [comment]
Although to features for it yet, the morgue is now accessible through the Pillbox hospital.
