### ISSUE TITLE
Double Weapon

### ISSUE THREAD

**Issue by RGDaviid** [InZidiuZ/op-framework-bug-tracker#4]
**Reporter:**
Davidk#2271

**Summary:**
When taking a weapon (a knife in my example) it stays in your back but also spawns another one in your hand.

**Steps to Reproduce:**
Just take it out of my Inv

**Expected Results:**
i expected for it to be removed from my back as i took it out. 

**Actual Results:**
Spawned another one in my hand. and kept the other one on my back.

## More Info

**Screenshots:**

**Game Resolution:**
1920x1080

**Player Data:**
doing /info i got 
Error running system event handaling function for resource op-base: citizen:/scripting/lua/scheduler.lua:41: Failed to ewxect
	stack traceback:
		commands/commands_server.lua:73: in upvalue "handler"
		citizen:/scripting/lua/scheduler/lua:219: In function <citizen:scritping:/scripting/lua/scheduler.lua:218>
	stack traceback:
		[C]: in funcction "error"
		citizen:/scipting/lua/scheduler.lua:41: in field  "CreateThreadNow"
		citizen:/scripting/lua/scheduler.lua:218: in function <citizen:scritping/lua/scheduler.lua:182>
**Notes:**
Can't paste the photo in :(

![image](https://user-images.githubusercontent.com/40771170/52525834-5e042000-2ca7-11e9-8a61-bcf65d9a756a.png)

**Comment by RGDaviid** [comment]
![image](https://user-images.githubusercontent.com/40771170/52525847-a6234280-2ca7-11e9-804f-a4d68098ed25.png)

**Comment by InZidiuZ** [comment]
This issue has been resolved. If the problem persists, please reopen the issue.
