### ISSUE TITLE
Two new skins (Official skins) to create good roleplay for "The Families" gang

### ISSUE THREAD

**Issue by Wescottz** [InZidiuZ/op-framework-bug-tracker#40]
**Suggester:**
Wescott - Wes#7238
 
**Summary:**
In order to create a good roleplay experience with one of the new streetgangs we have created we require 2 official skins that are part of the game but not yet in the game. We'd like these skins so we can provide proper RP for the server.

https://gta.fandom.com/wiki/Lamar_Davis
https://gta.fandom.com/wiki/Franklin_Clinton
 
**Reason:**
Roleplay purposes
 
**Economy:**
No

**Comment by InZidiuZ** [comment]
Hey,

The "Lamar Davis" character has been added, but Franklin won't be added due to possible complications.

**InZidiuZ**
*OP-FW Developer*
