### ISSUE TITLE
EMS needs Put in trunk function added to ambulance! press E when at the back of it

### ISSUE THREAD

**Issue by mystorydank** [InZidiuZ/op-framework-bug-tracker#41]
Mystorydank = discord , D. Story Senior moderator for legacy staff team

I think in the best intrest for roleplay to bring someone to the hospital for EMS is very important but the function to put someone into the trunk of the ambulance does not show the function to put someone into the vehicle. a normal vehicle has it but Medical vehicles need to have the ability to place someone into the trunk when they are down so we can bring them to the hospital.

This will increase the roleplay for not only the EMS but for everyone in the community to not have to worry about people dieing somewhere and EMS telling them they cannot bring them back to the hospital to let a doctor treat them , they would have to be treated on scene and i feel the option for more major injuries can improve the roleplay by adding a function to the ambulance to put someone into the trunk! thank you!

**Comment by InZidiuZ** [comment]
Hey,

The ability for EMS to use the /suspect [in/out] commands has been added.

**InZidiuZ**
*OP-FW Developer*
