### ISSUE TITLE
EMS helicopter is spawing with no keys so you have to hotwire the helicopters .

### ISSUE THREAD

**Issue by mystorydank** [InZidiuZ/op-framework-bug-tracker#42]
Mystorydank = discord / D. Story , senior moderator for legacy staff team

The helicopter for EMS when spawned it does not give a key so you can fly it right now and it requires a hotwire. i feel the adding the ability to have the key is important because if responding to a call very far away time is very crucial and no one wants to hear they had to hotwire the helicopter to come save them. EMS do not commit crimes!

This will help not only the EMS but the community as well by enganging in more roleplay with working functions and the helicopters getting the right attention and working efficiently! Thank you!

**Comment by InZidiuZ** [comment]
Unable to replicate. I do get a key whenever spawning in an EMS helicopter. Make sure your inventory isn't full, as it won't be able to give you the keys then.
