### ISSUE TITLE
Car Dealership

### ISSUE THREAD

**Issue by RGDaviid** [InZidiuZ/op-framework-bug-tracker#43]
- Office Doors stay locked for everyone else apart from the person me when i unlock them. 

- Vehicles sometimes double up on top of each other apparently. (Client sided issue.. Maybe have a way of deleting vehicles around and respawning them really fast?)

**Comment by InZidiuZ** [comment]
Have you had any further instances of the spawning issue?

**Comment by InZidiuZ** [comment]
Closed due to inactivity, and probably being fixed.
