### ISSUE TITLE
New life job change

### ISSUE THREAD

**Issue by Ronilf** [InZidiuZ/op-framework-bug-tracker#44]
So this happened last night after having to respawn at the hospital
![New Life issue](https://user-images.githubusercontent.com/51394914/59814675-c4dfb880-92db-11e9-89a6-f3755fb6873a.JPG)

**Comment by Ronilf** [comment]
I had to go to the job center and re-acquire my transporter position to fix it. I don't think making me a LEO was intentional esp since i haven't applied for it

**Comment by InZidiuZ** [comment]
Definitely a mistake from a staff member, very likely me as I believe I may have set some people to police by accident. Apologies for the inconvenience.
