### ISSUE TITLE
Not a bug but a request for truckers

### ISSUE THREAD

**Issue by Ronilf** [InZidiuZ/op-framework-bug-tracker#45]
Down by the HQ for transporters the pick up location does not have a way into it w/o having to crash through a gate. I was wondering if it would be possible to put on in at the location noted in the picture. If you need a better idea for the location i would be happy to take a better screen shot show
![Trucker Req](https://user-images.githubusercontent.com/51394914/59814861-56e7c100-92dc-11e9-8589-f1c8f956b07d.JPG)
ing exactly where its at in relation to the job pick up location.

**Comment by InZidiuZ** [comment]
If you're referring to [this](https://gyazo.com/323d562c3e1b57c4db7e8cda96a450be) one, then you're easily able to walk through it. You're not required to drive the phantom through the gate...

**Comment by InZidiuZ** [comment]
No further activity.
