### ISSUE TITLE
Unable to store vehicle

### ISSUE THREAD

**Issue by Ronilf** [InZidiuZ/op-framework-bug-tracker#46]
Unable to sotre my Phantom at the p[aleto garage.
![Storage](https://user-images.githubusercontent.com/51394914/59817823-02960e80-92e7-11e9-82c3-8d0421290843.JPG)

**Comment by Ronilf** [comment]
![Storage 2](https://user-images.githubusercontent.com/51394914/59818047-e8106500-92e7-11e9-9fa4-087fa404dab9.JPG)
Happened again at Court House garage

**Comment by InZidiuZ** [comment]
Can you do /info and attach the information?

**Comment by Ronilf** [comment]
ill have to get on and see if i can get it to happen again if it does ill definitely post it for you.

**Comment by InZidiuZ** [comment]
Will go ahead and close this, as it was on the test server. But if it happens again, please DM me so we can get it sorted out, once and for all.
