### ISSUE TITLE
mechanic unable to get calls from favourites in phone

### ISSUE THREAD

**Issue by nilmartwitch** [InZidiuZ/op-framework-bug-tracker#48]
i had a txt off officer rae saying she messaged me in the mechanic tab in phone but i never got any message i am employed as a tow truck driver

**Comment by WilsonPlays** [comment]
Apparently Some people are getting it. Some People are not

**Comment by InZidiuZ** [comment]
This might be related to #59, and is being investigated.

**Comment by InZidiuZ** [comment]
#59 has now been resolved, but due to the lack of information given, I can't say whether this issue has been resolved too. If it persists, please create another issue using the template and giving as much information as possible.
