### ISSUE TITLE
Tattoos disappeared 

### ISSUE THREAD

**Issue by brookestellete** [InZidiuZ/op-framework-bug-tracker#49]
My tattoos are disappearing after my game crashes.

**Comment by InZidiuZ** [comment]
Hey,

Could you provide some more information?

* Please do /info in-game and attach a screenshot of it here,
* Do you have a timestamp as to when this happened?
* Have you been able to reproduce it?
* How long after purchasing the tattoo, did your game crash?

**InZidiuZ**
*OP-FW Developer*

**Comment by InZidiuZ** [comment]
Closing due to no response. If this is still an issue, comment & I'll reopen it.
