### ISSUE TITLE
Terminal Locked Doors

### ISSUE THREAD

**Issue by WilsonPlays** [InZidiuZ/op-framework-bug-tracker#51]
**Suggester:**
WilsonPlays#6969

**Summary:**
Need Locks on Doors to prevent people from accessing the computer

**Reason:**
This will stop people buying their own mats. Keeps Mechanics in business

**Comment by InZidiuZ** [comment]
Hey,

This has now been added, and will go live with the next patch.

**InZidiuZ**
*OP-FW Developer*
