### ISSUE TITLE
EMS Injury Viewing

### ISSUE THREAD

**Issue by iMStokes** [InZidiuZ/op-framework-bug-tracker#54]
Suggestion: **Script for injury viewing**
From: _X-133 Jax Winston_

If this is already implemented and overlooked, please feel free to move on.

Upon testing and a few calls, we noticed we were unable to view injuries of the people at the scene. Personally feel whether we use the old script or a new one for this framework, one needs to be in place so that EMS can properly assess injuries for patients. Especially since the calls we went to were "gunshot wounds" - and because he was moved we were unable to see any damage and have to rely on stories of those at the scene (only the suspect was there)

If we are to base injuries off of stories of people there or even the patient, we cannot properly treat or run out the situation as needed. If someone is shot in the head 4 times and we have to walk up and be like "Hello, sir can you hear me, and tell me what happened?" and they simply say "i was shot in the toe" - it's going to cause a storm among people. And even if they wanted to die, and we have to ask the dead person to properly describe what happened, the immersion is already gone. 

Believe this would help with increased roleplay and proper diagnosis for everyone involved in the situation. :)

**Comment by InZidiuZ** [comment]
Hey,

A way more in-depth injury system has been planned, and should arrive in the next couple of weeks. If delayed, the old system will be temporarily added until the new system is in.

**InZidiuZ**
*OP-FW Developer*

**Comment by InZidiuZ** [comment]
Closing this till the new system is WIP.
