### ISSUE TITLE
Bug about 911 messages

### ISSUE THREAD

**Issue by itsBendz** [InZidiuZ/op-framework-bug-tracker#57]
There is a bug where cops cant reply to 911 messages and we cant see the number it is coming from. It only gives the option to delete the message or go to the GPS location.

**Comment by InZidiuZ** [comment]
Hey,

I believe this was changed with the phone after the twitter update. As the phone isn't made by us, I am not certain as to what's causing this, but it will be investigated.

**InZidiuZ**
*OP-FW Developer*

**Comment by InZidiuZ** [comment]
After the next patch, it will be possible to respond to job-messages.
