### ISSUE TITLE
/report not working as intended.

### ISSUE THREAD

**Issue by Anderzenn** [InZidiuZ/op-framework-bug-tracker#59]
**Reporter:** Anderzenn#0069

**Summary:** When you do /report it will sometimes bug out and thrown an error message.

**Steps to Reproduce:** I am not entirely sure, but I just did /report, it was broken for my friend as well.

**Expected Results:** /report should send a message to staff, as well as show you the message you sent to them.

**Actual Results:** /report sends an error message in chat instead.

### More Info
**Screenshots:** 
![image](https://user-images.githubusercontent.com/12025450/59965660-87647080-9511-11e9-8d27-317a160d2ee5.png)

![image](https://user-images.githubusercontent.com/12025450/59965667-9d723100-9511-11e9-9f73-d7cf868084c1.png)

**Game Resolution:** 3440x1440

**Player Data:**
Character ID: 25 - Job Data: Medical, Los Santos Medical Center, Assistant Director
Timestamp: 2019-06-22 16:17:54

**Comment by InZidiuZ** [comment]
This is a known issue, and the cause is also what's bugging out the phones. Been investigating this, but so far haven't been figured out what's causing it, looks FiveM related, though.

**Comment by InZidiuZ** [comment]
This issue has been resolved.
