### ISSUE TITLE
Handcuffs

### ISSUE THREAD

**Issue by liner601** [InZidiuZ/op-framework-bug-tracker#6]
**Reporter:**
liner60

**Summary:**
you can punch while handcuffed

**Steps to Reproduce:**
1. get handcuffed
2. punch 

**Expected Results:**
nothing happens

**Actual Results:**
You punch

notes: DisableControlAction

**Comment by InZidiuZ** [comment]
You should no longer be able to punch while handcuffed. If the problem persists, please reopen the issue.
