### ISSUE TITLE
Gun License Permanent Revoke

### ISSUE THREAD

**Issue by Wrothgar** [InZidiuZ/op-framework-bug-tracker#60]
Suggester: @Wrothgar#1293
Summary: What if after you had your gun license revoked for a crime (murder, robbery, etc) you couldn’t buy a new license due to your criminal record involving a weapon and have to buy a gun from someone who is illegally selling guns.

Reason: It would make it more realistic for RP.

Economy: It would affect the economy a little bit because gun dealers obviously want to make a profit so they sell the guns for more expensive than they usually are.

**Comment by InZidiuZ** [comment]
Hey,

Right now I don't see this being a thing, but in the future, police may have the ability to prevent common offenders from purchasing licenses, driving cars, etc.

**InZidiuZ**
*OP-FW Developer*
