### ISSUE TITLE
Possible item duplication when retrieving a vehicle.

### ISSUE THREAD

**Issue by RoyalWolfXD** [InZidiuZ/op-framework-bug-tracker#61]
I was working at Maze Bank Arena, as a reporter with my news van. I had to relog and retrieved my vehicle to find that when I returned my van was still there. Both vans had a key that I had stored in the trunk. I don't know if other items would duplicate or if any vehicle trunk would work. I did rejoin the same district, which I assume plays a role in the original vehicle still being in it's parking space. 

I didn't test or remove the items. I left the van the was originally there in it's place, this occurred on district 4. If there's anything else I can provide to help I will.

**Comment by InZidiuZ** [comment]
Hey,

There are already multiple systems in place to avoid this from being used in item duplication.

* Each inventory has its own unique identifier, which is retrieved from the plate, and not the vehicle. This means you wouldn't be able to have a secondary guy access the other vehicle while you are in the original one.
* Vehicle inventories are unloaded when you log out to prevent them from being loaded simultaneously and allowing for temporary item dupes on another one.

I appreciate the concern, but as this most likely won't be an issues, I will close the issues. :)

**InZidiuZ**
*OP-FW Developer*
