### ISSUE TITLE
Police Chopper Camera

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/op-framework-bug-tracker#62]
**Suggester:**
Who is suggesting this? Please include discord name.
Sercan#1192

**Summary:**
Write a short summary of what your suggestion is about.
Police chopper camera to be able to lock on vehicles.

**Reason:**
Why would your suggestion be a good addition to Legacy?

Usefull for PD in pursuits.

**Comment by Wescottz** [comment]
No, because it locks on and follows through the map. Even when you try to escape the helicopter in tunnels, etc.

**Comment by InZidiuZ** [comment]
Hey,

This has been added, and will go live with next patch.

**InZidiuZ**
*OP-FW Developer*
