### ISSUE TITLE
Police Radar

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/op-framework-bug-tracker#63]
**Suggester:**
Who is suggesting this? Please include discord name.
Sercan#1192

**Summary:**
Write a short summary of what your suggestion is about.
Police radar:
While having your radar and your phone up the phone bottom part disappears behind the radar.
Maybe scale the radar a bit down or move the location.
**Reason:**
Why would your suggestion be a good addition to Legacy?

Usefull for PD to be able to see the phone and radar in the same time

**Comment by InZidiuZ** [comment]
Won't be done now, temporarily remove the /radar when using the phone.

**Comment by InZidiuZ** [comment]
Quick update to this: whenever opening your phone & having the radar open, the radar will automatically hide until the phone is taken down again.
