### ISSUE TITLE
Police/EMS Automatic Timestamps

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/op-framework-bug-tracker#64]
**Suggester:**
Who is suggesting this? Please include discord name.
Sercan#1192

**Summary:**
Write a short summary of what your suggestion is about.

Police timestamps logs. 

**Reason:**
Why would your suggestion be a good addition to Legacy?

So its easy to keep track on who is active, so we can get rid of the inactive ones

**Comment by InZidiuZ** [comment]
Hey,

This has now been added for both police & ems in discord.

**InZidiuZ**
*OP-FW Developer*
