### ISSUE TITLE
Truck shop at port

### ISSUE THREAD

**Issue by Dinoreaper5** [InZidiuZ/op-framework-bug-tracker#65]
Every time i repair my tow truck's body, The truck disappears

**Comment by InZidiuZ** [comment]
Hey,

I will need some additional information to investigate this.

* Do /info in-game and attach a screenshot of it here.
* What truck is it? Please include the plate number too.
* Are you able to reproduce this issue, even after a relog? If able to reproduce after a relog, try clearing your cache, and see if you're still able to.

**InZidiuZ**
*OP-FW Developer*

**Comment by InZidiuZ** [comment]
Will close this as it's the same issue in #67.
