### ISSUE TITLE
JOURNALIST ISSUES & IDEAS

### ISSUE THREAD

**Issue by SoniMatt** [InZidiuZ/op-framework-bug-tracker#66]
For the reporter/journalist the camera can't be seen by most people. Also the journalist job NEEEEEDS the same alerts that Police get, or i just drive around doing nothing not knowing whats going on... Very boring job if i don't know whats happening in the city. ALSO Camera & Boom Mic is stuck in my hands when i unequipped them, example https://imgur.com/a/3tiHj06

**Comment by InZidiuZ** [comment]
Hey,

I've made some changes as to how the camera/mic are spawned to hopefully fix the issue of them not being visible to some.

The blips however, won't be added to the reporter job, for now. This is to prevent too much of a chaos & mess whenever something goes down.

**InZidiuZ**
*OP-FW Developer*
