### ISSUE TITLE
Default "Male" Skin

### ISSUE THREAD

**Issue by MrBiscuitweener** [InZidiuZ/op-framework-bug-tracker#69]
I created a new character yesterday and chose the "male" category then the "priest" skin. and then i was told by multiple people in the city that i was invisible. i relogged twice and it was still the same. i finally ran into an admin and they made me change my skin. just wanted to bring this to attention so that nobody is taking advantage of an invisible character. Also i would like to use the priest skin :)

**Comment by InZidiuZ** [comment]
Hey,

A ton of characters which would go invisible at times (including the priest model) has now been fixed & swapped out with a separate version of themselves which won't go invisible. You'll now be able to recreate your character (or ask for a /reskin through /report) to use the priest skin again.

The changes will go live after the patch.

**InZidiuZ**
*OP-FW Developer*
