### ISSUE TITLE
Can't use anything in inventory.

### ISSUE THREAD

**Issue by johnnip** [InZidiuZ/op-framework-bug-tracker#7]
Reporter:
Manic#9676

Summary:
Can't use anything in inventory, I can get into the inventory but not take anything out
Steps to Reproduce:
Not sure, I tried to use a bandage on myself because I tripped a couple of times and was low on health, and it didn't let me. I tried to use a repair on a vehicle later on and that worked, but the repair kit stayed in my inventory after use. I also tried to lockpick a vehicle, and it wouldn't use the lockpick.
Expected Results:
Not being able to use anything I think

Actual Results:
Not being able to use anything I think

More Info
Screenshots:
Well I guess I fucked up because I already logged off

Game Resolution:
1920x1080 I believe
Player Data:
Logged off
Notes:
The repair kit worked but stayed in my inventory.

**Comment by InZidiuZ** [comment]
Not all items have been made functional yet, but they should all be in an upcoming version. Repair kits break every now and then, but not always, they also only repair your vehicle slightly, and not fully.
