### ISSUE TITLE
Suggestion: /steal cooldown / time to complete

### ISSUE THREAD

**Issue by RemedyUK** [InZidiuZ/op-framework-bug-tracker#70]
People are complaining about others constantly stealing from people which is causing actual RP'ers to complain, I thought about the issue and came up with 2 possible solutions to the issue at hand.

1. Add a cool down to the /steal command of 30-60 minutes. (Once someone has used the /steal command successfully, they cannot use it again for this time.)

2. Make the /steal command similar to that of hotwiring a vehicle, 45-60 seconds to complete, police are alerted. (It should hopefully force people to be more careful where they hold people up as the police could be nearby to intercept).

**Comment by N8teZero** [comment]
I agree that stealing should not be as convenient as it is. Both options you've presented seem like they would do the trick.

**Comment by Roocket4** [comment]
I like the second one a lot, would definitely vote for that!

**Comment by InZidiuZ** [comment]
Hey,

I do agree constant robbing is a problem, but I'm not a huge fan of what's suggested here. Adding a cooldown to it seems too forced to me, and I don't believe it would stop a whole lot of robberies. People that do like to constantly rob, most likely don't get the chance to rob more than one people every hour anyways.

Adding a timer to how long it takes is a possibility, but I still feel like it would be too forced at this time, and don't want to spend time on that right now.

What I have done though, to combat the issue, is remove the ability for people to /steal someone that has their hands up, to make it less appealing for the criminals.

**InZidiuZ**
*OP-FW Developer*
