### ISSUE TITLE
/taxifare can't set custom prices

### ISSUE THREAD

**Issue by essjaybee** [InZidiuZ/op-framework-bug-tracker#71]
Hey, now that phones are working again it makes more sense to taxi. But I have a issue with /taxifare.
/taxifare help and /taxifare show work. But setting a custom initial, like /taxifare initial 5 doesn't do anything, and I've tried different variations of it. 5.0 $5.0 5,0 etc. It always tells me invalid use of command and refers to /taxifare help, which does list those actions.

**Comment by InZidiuZ** [comment]
Hey,

This issue has been resolved. The fix will go live after next patch.

**InZidiuZ**
*OP-FW Developer*
