### ISSUE TITLE
Police armory logs

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/op-framework-bug-tracker#73]
**Suggester:**
Who is suggesting this? Please include discord name.
Sercan#1192

**Summary:**
Write a short summary of what your suggestion is about.

Police Armory/evidence locker logs. 

**Reason:**
Why would your suggestion be a good addition to Legacy?

So there is any record of people stealing from those.

**Comment by InZidiuZ** [comment]
There are already logs for whenever a secondary inventory is opened, but to create logs for whenever something is moved/stacked/swapped, would be too much.

**Comment by InZidiuZ** [comment]
Evidence lockers also wipe after every restart. Or at least they're supposed to.
