### ISSUE TITLE
Spawn point in PD for only PD member(s)

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/op-framework-bug-tracker#74]
**Suggester:
Who is suggesting this? Please include discord name.**
Sercan#1192

**Summary:
Write a short summary of what your suggestion is about.**

PD being able to spawn in one of the police stations

**Reason:
Why would your suggestion be a good addition to Legacy?**

Makes it safer for PD member, as we spawn in we would have to run all the way back to PD. There is also a chance that someone would take them hostage as they are wearing uniform.

**Comment by InZidiuZ** [comment]
At this time, this will not happen.
