### ISSUE TITLE
PD boss menu

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/op-framework-bug-tracker#75]
**Suggester:
Who is suggesting this? Please include discord name.**
Sercan#1192

**Summary:
Write a short summary of what your suggestion is about.**

PD boss menu. Being able to recruit, fire and manage salary. 

**Reason:
Why would your suggestion be a good addition to Legacy?**

Makes it easier for us in the High command to recruit or fire people. As it is now we are not able to remove inactive people manually. We had a guy that was removed which decided to rob the armory, which also ruins the economy.

**Comment by InZidiuZ** [comment]
Salary management won't be a thing, but eventually adding some way to easily remove people, will probably be.

Also, if the armory robbery happened after OP-FW, please give me his steam profile so I can ban him.

**Comment by InZidiuZ** [comment]
This will be sorted out privately.
