### ISSUE TITLE
PD EUP menu

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/op-framework-bug-tracker#76]
**Suggester:
Who is suggesting this? Please include discord name.**
Sercan#1192

**Summary:
Write a short summary of what your suggestion is about.**

EUP menu in the locker room, so pd members can change from city uniform to county uniform.

**Reason:
Why would your suggestion be a good addition to Legacy?**

Makes it easier for us to roleplay when we wanna go outside the city in the right vehicle/uniform.

**Comment by InZidiuZ** [comment]
From what I know, there's no EUP menu for the version of EUP we use, therefor no. There's plans to add a more complex outfit system though.
