### ISSUE TITLE
The items came back again after i die 

### ISSUE THREAD

**Issue by jehadhas** [InZidiuZ/op-framework-bug-tracker#78]
first that's happened by mistake , but i did't again to make sure it is a glitch .

The glitch is when someone killed you , and you are in the cool-down you press F8 and type Quit

and re-connect to the server again , you will respawn again without losing your items 

i hope you fix it  thanks you

**Comment by InZidiuZ** [comment]
Hey,

If you log out while dead now, you will automatically be checked in at the hospital when logging back. You will also have a 100% of being mugged. This will go live after next patch.

**InZidiuZ**
*OP-FW Developer*
