### ISSUE TITLE
Can't view Money

### ISSUE THREAD

**Issue by ConorTTV** [InZidiuZ/op-framework-bug-tracker#8]
When I do /bank or /cash I cannot see how much I have. It is not view able
![66e2375c107b920ab049040dc2bff07f](https://user-images.githubusercontent.com/44046798/56854767-e5a61600-6909-11e9-82c4-f819138c15a0.jpg)
...

**Comment by InZidiuZ** [comment]
Try to relog, and also use the template. This won't let me fix anything.

**Comment by InZidiuZ** [comment]
If this issue persists, please DM me on discord.
