### ISSUE TITLE
Can't drop DC'd people whom you've carried

### ISSUE THREAD

**Issue by sammikinsrox** [InZidiuZ/op-framework-bug-tracker#80]
If someone disconnects while you are carrying them, they are permanently glued to you. This causes some very unintended side-effects with the physics. Perhaps when the person disconnects the ped should become automatically uncarried.

Video: https://streamable.com/uyb66

**Comment by InZidiuZ** [comment]
Hey,

This will be resolved after next patch.

**InZidiuZ**
*OP-FW Developer*
