### ISSUE TITLE
Police Bike Radar

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/op-framework-bug-tracker#82]
**Suggester:**
Who is suggesting this? Please include discord name.
Sercan#1192

**Summary:**
Write a short summary of what your suggestion is about.
The police Bike does not have a radar.

**Reason:**
Why would your suggestion be a good addition to Legacy?

Usefull for PD to be able to use the radar.

**Comment by InZidiuZ** [comment]
Hey,

The police bike now has access to the radar.

**InZidiuZ**
*OP-FW Developer*
