### ISSUE TITLE
No Possible way of replacing lost bonnet/hood on....

### ISSUE THREAD

**Issue by SkippingBaboon** [InZidiuZ/op-framework-bug-tracker#83]
... the JoBuilt Phantom Truck used for Transporting.

Not sure if this a bug or what, but have tried every possible Mechanic/Repair avenue and also tried destroying truck, retrieving truck. Has also been 3 resets since Bonnet went missing, and it only fell off whilst repairing engine -.-

**Comment by InZidiuZ** [comment]
Hey,

After next patch this issue should be fixed.

**InZidiuZ**
*OP-FW Developer*
