### ISSUE TITLE
[Suggestion] Make EMS able to lock elevator to roof

### ISSUE THREAD

**Issue by Anderzenn** [InZidiuZ/op-framework-bug-tracker#86]
**Suggester:**
Z-105 Brandon Whittle | Anderzenn#0069

**Summary:**
EMS should be able to lock the elevator leading to the roof of the hospital.

**Reason:**
I feel that this would be a good addition to the EMS since access to the hospitals roof should only be for the actual EMS seeing as it's where we bring out and store our MedEvac helicopter as well as it being a hospital we don't want to risk patients with suicidal thoughts getting onto the roof and jumping off. As well as just general security concerns.

**Economy:**
This will not affect the economy

**Comment by InZidiuZ** [comment]
Hey,

The roof teleporter(s) have now been made only accessible for EMS.

**InZidiuZ**
*OP-FW Developer*
