### ISSUE TITLE
paid for vehicle

### ISSUE THREAD

**Issue by Revo1848** [InZidiuZ/op-framework-bug-tracker#87]
i have paid for a tow truck and a bf400 and stored them in my garage and checked and relogged but i cant get my vehicles i clicked f8 and it said end of error i cant say anuthing else apart from it not being there.

**Comment by InZidiuZ** [comment]
> i cant say anuthing else apart from it not being there

Yes, yes you can.

Please fill out the bug-report template found in "Code", will need more information to investigate this.

**Comment by InZidiuZ** [comment]
Until more information is provided, I will close this. Feel free to either create another issue. or comment here so I can reopen it later.

**Comment by Revo1848** [comment]
when i click vehicle list it backs me out of the whole menu back to start to press to e access garage 
![FiveM 26_06_2019 12_19_01](https://user-images.githubusercontent.com/50557710/60175994-fc36f380-980c-11e9-9568-f77e61d3603a.png)

**Comment by Revo1848** [comment]
btw u can re open the issue. Just so u can keep track

**Comment by Revo1848** [comment]
are u going to re open or should i make a new one?

**Comment by Revo1848** [comment]
i cant find the bug format could u re-open this issue

**Comment by InZidiuZ** [comment]
https://github.com/InZidiuZ/op-framework-bug-tracker - I'll open it when I have the information I need.

**Comment by Revo1848** [comment]
ok
