### ISSUE TITLE
Bug: Bought advanced repair kit, got nothing and had to buy again.

### ISSUE THREAD

**Issue by essjaybee** [InZidiuZ/op-framework-bug-tracker#88]
Reporter: Tommy Thorpe / OMGPointless#1823

Summary: Took out money to buy an advanced repair kit, already had a basic on me, bought the item. Perhaps was too fast on K and opened inventory, and kit wasn't there.

Steps to Reproduce: This whole thing basically reduced my bank balance by 50%, I'd rather not take steps to reproduce.

Expected Results: An advanced repair kit in my pocket first attempt, and not having to spend 4000 for it.

Actual Results: Got "Attempting a purchase of tool 35" in F8 console twice, no errors or other debug in the console during that time which makes me assume it might have been a race condition due to me being eager, or a conflict with the basic repair kit

Have video of it happening: https://www.youtube.com/watch?v=bvuBTi7JZYk&feature=youtu.be
(if video haven't been cut yet, I take out the money at 2:10, and buy the advanced repair kit one minute later

My bank account will also appreciate the 2000 or an extra advanced repair kit, but understand if you have a no refund thing. Just got pretty sad inside as 2000 still is a lot for me. Have screenshot of my id and steam id for the event. If I can assist in any way feel free to contact me on Discord.

**Comment by InZidiuZ** [comment]
In your inventory you had "x2 Vehicle Key", try splitting that stack, and then opening your inventory. Your repair kit should be under that key.

**Comment by essjaybee** [comment]
Crap. Think I know what you mean, and pretty sure I was dumb enough to put that in a bush thinking it was duplicate key from something. :( it's not in my inventory anyway so I'll just have to take the loss.

thanks for checking it out.

**Comment by essjaybee** [comment]
and when I review the video now it seems so obvious, yeah it was totally there. I must have thrown that key out after storing my last vehicle so maybe some lucky guy ran into it at court house

**Comment by InZidiuZ** [comment]
Yea not entirely sure as to why unstackable items sometimes stack, but will look into it in the future, together with some other minor inventory issues. Will close this though.
