### ISSUE TITLE
Bicycle Stamina

### ISSUE THREAD

**Issue by N8teZero** [InZidiuZ/op-framework-bug-tracker#89]
Reporter: Nate

Summary: The limited stamina prevents long use of the quick pedaling of an variation bike(BMX, Scorcher, etc). I think the stamina should be increased or make an exception for people on bikes, as it's quite annoying the way it is. I am trying to get back into BMX tricks, but finding it difficult to maintain speed.

Steps to Reproduce: Ride bike, enable fast pedaling(Caps Lock), and watch as your stamina quickly runs out, and then comes back randomly.

**Comment by Revo1848** [comment]
i understand u want to do tricks, but if u are just riding a bmx for fun u can spam jump and hold shift and u go faster

**Comment by InZidiuZ** [comment]
Hey,

Stamina has now been made unlimited whenever on a bicycle.

**InZidiuZ**
*OP-FW Developer*
