### ISSUE TITLE
Can't close ATM

### ISSUE THREAD

**Issue by Waywardxx** [InZidiuZ/op-framework-bug-tracker#9]
Reporter: Viagrafalls#4699

Summary: After i withdrew money from the atm and clicking on the Close menu button, i couldn't close the ATM UI. I tried all the Keybinds. 

Steps to Reproduce: Go to an ATM, Withdraw some money. Close the UI with the Close Menu button. After the UI closes, press E instantly, wait for the message to pop up saying "Press E to use ATM" deposit the money again and try to close the UI.

Expected Results: It should close the menu

Actual Results: ATM UI freezes and unable to close without quitting the game.

Also, After this is done, the money doesn't show as deposited. It stays at the same amount.

**Comment by InZidiuZ** [comment]
I believe this issue was fixed a few days ago, not entirely sure though. I am, however, unable to replicate it after the latest ATM-changes. If the issue still persists please DM me on discord.
