### ISSUE TITLE
bought vehicles not in garage

### ISSUE THREAD

**Issue by Revo1848** [InZidiuZ/op-framework-bug-tracker#90]
Reporter: Who is reporting this? Please include discord name.Revo-_-#4125 

Summary: Write a short summary of what you're experiencing.i bought a tow truck and a bf400(bike) and it seems to not be in my garage anymore

Steps to Reproduce: Include what steps that are needed in order to reproduce the issue.
put a vehicle in the garage and try to take it out and it might not be there anymore
Expected Results: What are the expected results?
store my vehicle in the garage and come back later to get it
Actual Results: What are the actual results?losing my vehicle and ownership of the vehicle by the looks of it.
![FiveM 26_06_2019 12_19_01](https://user-images.githubusercontent.com/50557710/60198160-e3443780-9838-11e9-9144-22ef4f59f557.png) these are the F8 logs.
Screenshots: If suitable, include some screenshots. You also have to include screenshots of your F8 console.above

Game Resolution: What is your game's resolution?
1920x1080
Player Data: Write /info whilst ingame and provide the information you're given.
![image](https://user-images.githubusercontent.com/50557710/60200970-2903fe80-983f-11e9-8b9c-fbb30f3ca5f6.png)

Notes: For anything else noteworthy.nothing else that could help.

**Comment by InZidiuZ** [comment]
Please include the "More Info" part too.

**Comment by Revo1848** [comment]
i have edited and added it

**Comment by InZidiuZ** [comment]
You're given more data in /info... could you attach a screenshot of it?

**Comment by Revo1848** [comment]
added it

**Comment by InZidiuZ** [comment]
This has now been resolved, also made some changes to prevent this from happening again in the future.

**InZidiuZ**
*OP-FW Developer*
