### ISSUE TITLE
Chat input gets stuck when you die

### ISSUE THREAD

**Issue by sammikinsrox** [InZidiuZ/op-framework-bug-tracker#95]
If you die while the chat input is open, the chat input gets stuck open and you can no longer type. A simple way to reproduce this is to fall from a far height while you're trying to type something, do not finish your input and press enter. Your chat input will be stuck open and the only way to fix it is to relog.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
