### ISSUE TITLE
Cars/bikes handling

### ISSUE THREAD

**Issue by EddyHonein** [InZidiuZ/op-framework-bug-tracker#96]
I think cars and bikes handling should be custom to become more realistic and belts should be removed for bikes.
I assume this is being worked on but just saying. 
Thanks. 🙂

**Comment by InZidiuZ** [comment]
Car & bike handlings are already custom, and belts have no effect for bikes.

**Comment by EddyHonein** [comment]
Oh ok but it feels so fast/broken when going left to right with bikes.
Thanks anyways.
