### ISSUE TITLE
Police LSPD FPIU

### ISSUE THREAD

**Issue by FossiiLs** [InZidiuZ/op-framework-bug-tracker#97]
Please make the FPIU stronger, I am all for RPing with the mechanics to get my vehicle fixed but the FPIU is pretty much made out of cardboard and constantly having to get is fixed is very frustrating. Also maybe a cool design for the police vehicles. Something other than the normal black and white would be cool. Thank you.

**Comment by InZidiuZ** [comment]
Hey,

When you say that it breaks easily, are you talking about actual engine damage, or just the deformation?

I also don't do assets, that's mostly Karpenko.

**InZidiuZ**
*OP-FW Developer*

**Comment by FossiiLs** [comment]
Engine damage and deformation. There are times when I know where the engine will be slightly damaged but the body is completely messed up. This will cause you to not be able to turn as easily like normal which is understandable but it'll make it to where you cant even reach a mechanic due to not being able to turn and slamming into something destroying the engine, So the mechanics have to come to you and it cost me around 1.5k for the tow and the fix which is expensive now. I appreciate you reading this. Thank you.

**Comment by InZidiuZ** [comment]
Okay, already got Karpenko on this, but as he's on vacation we'll wait for him to come back before he does something about it, I will close this though. Would recommend just /impounding it until then, and spawning a new one in at PD.
